# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: dotnet

on:
  push:
  pull_request:
    branches: 
      - '*'
    
env:
  DOTNET_VERSION: '8.x'

jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        working-directory: ./ParkingZoneApp
        run: dotnet restore

      - name: Build
        working-directory: ./ParkingZoneApp
        run: dotnet build --configuration Release --no-restore
    
      - name: Test
        working-directory: ./ParkingZoneApp
        run: dotnet test --no-restore --verbosity normal